### ISSUE TITLE
How do I change the language of the buttons?

### ISSUE THREAD

**Issue by 809825706** [BigIskander/Handwriting-keyboard-for-Linux.#3]
![image](https://github.com/user-attachments/assets/e7a1f8fb-f586-430e-87da-0bb90553a57d)

The system language is Chinese while the button language is Russian? how to change it?

**Comment by BigIskander** [comment]
Text on buttons does not depends on system language.
As of now it is hardcoded.

To change this text it is needed to be changed in code, then recompile the program.
