### ISSUE TITLE
Can you set buttons for some common Chinese punctuation?

### ISSUE THREAD

**Issue by 809825706** [BigIskander/Handwriting-keyboard-for-Linux.#4]
Hi, this is the only Linux handwriting input method I could find. However, I have some suggestions to optimise its use.

It is well known that ORC doesn't recognise punctuation very well, especially with characters. Why don't you create a set of buttons for punctuation so we can click on it to quickly enter punctuation.

**Comment by BigIskander** [comment]
Accepted your pull request. Added common Chinese punctuation.
